import Head from "next/head";
import { fetchTradeKline } from "@/api";
import { GetServerSideProps } from "next";
import { useEffect } from "react";

type Props = {
  price: string;
  cur: string;
  base: string;
};

export default function Home({ cur, base, price }: Props) {
  const curRel = `${cur}/${base}`;

  // useEffect(() => {
  //   window.location.href = `https://ace.io/trade/${curRel}`;
  // }, [curRel]);

  return (
    <>
      <Head>
        <title>{`${curRel}: ${price} 陳居仲`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1>{`${curRel}: ${price}`}</h1>
      </main>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  console.log("");
  console.log("---------- getServerSideProps ----------");
  let price = "0";
  try {
    const {
      data: { status, attachment },
    } = await fetchTradeKline({
      baseCurrencyId: 1,
      tradeCurrencyId: 2,
      type: 60,
      limit: 24,
      interval: "",
    });
    if (status === 200) {
      price = attachment?.length
        ? attachment[attachment.length - 1].current
        : price;
    }
  } catch (err) {
    console.log(err);
  }
  return {
    props: {
      price,
      cur: query.cur,
      base: query.base,
    },
  };
};
