import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { fetchTradeKline } from "@/api";
import { GetStaticProps, GetStaticPaths, GetServerSideProps } from "next";
import { useEffect } from "react";

type Props = {
  price: string;
};

export default function Home({ price }: Props) {
  console.log("f2e", price);
  // useEffect(() => {
  //   window.location.href = "https://ace.io/";
  // }, []);
  return (
    <>
      <Head>
        <title>我是陳居仲</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta
          name="google-site-verification"
          content="oQSbYUy8YC6-tA_NzADuXGrQ5Mqje2Ln9wBj77n2PPc"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>首頁</h1>
      </main>
    </>
  );
}
